[project]
name = "chat-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.3",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.16.1",
    "dj-database-url>=2.0.0",
    "groq>=1.1.2",
    "gunicorn>=23.0.0",
    "psycopg>=3.2",
    "python-dotenv>=1.2.2",
    "whitenoise>=6.7.0",
]

[tool.mypy]
python_version = "3.12"
strict = false
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
exclude = ["uniapi/migrations/"]

[dependency-groups]
dev = [
    "mypy>=2.3.0",
    "ruff>=0.16.3",
]
